### ISSUE TITLE
Problem in eval.py

### ISSUE THREAD

**Issue by ZhangYu1ing** [wjy199708/my_point_painting#3]
Hi, we are going to achieve PointPainting algorithm as well. However, we met the bug as shown below. Since we saw that you modified line 57 in your eval.py file compared to the original author's code. So we wonder if you have the same issue as us. Thanks in advance.

========= **our problem** ======================
Traceback (most recent call last):
  File "eval.py", line 89, in <module>
    evaluate(test_data_prepare(root), model)
  File "eval.py", line 57, in evaluate
    augmented_lidar_cam_coords = torch.tensor(
**ValueError: only one element tensors can be converted to Python scalars**

**Comment by 304886938** [comment]
I met the same problem. Have you solved it now？

**Comment by ZhangYu1ing** [comment]
I think the problem is that the type of augmented_lidar_cam_coords is 'tuple'. In the train.py, you can find the augmented_lidar_cam_coords as well, however, its type is 'list' with 'tensor' elements. I have not entirely solved this problem. Hope you could get some inspiration and solve it. Please let me know if you successfully solve this bug.

**Comment by ZhangYu1ing** [comment]
> I met the same problem. Have you solved it now？

Do you have any process in eval.py? Have you successfully implemented it?

**Comment by 304886938** [comment]
Sorry,I have tried many times,but failed. However, I think the core of the code is in the dataset.py. You can pay more attention to it.

**Comment by typhoonlee** [comment]
May I ask the weight file used in the semantic segmentation stage
On what data set is “deeplab_20epochs.pth” pre-trained?
Is it the data set of the semantic segmentation part of kitti?
